### ISSUE TITLE
tensorflow:AutoGraph could not transform bound method ParameterShift.differentiate_sampled

### ISSUE THREAD

**Issue by thubregtsen** [tensorflow/quantum#206] opened 2020-04-18 11:17 UTC
Filing bug report due to explicit request in warning message: "Please report this to the TensorFlow team."

Running code from: https://www.tensorflow.org/quantum/api_docs/python/tfq/layers/ControlledPQC

Specific bit of code:
```
import tensorflow as tf
import tensorflow_quantum as tfq

import cirq
import sympy
import numpy as np

# visualization tools
%matplotlib inline
import matplotlib.pyplot as plt
from cirq.contrib.svg import SVGCircuit
```

```
bit = cirq.GridQubit(0, 0) 
model = cirq.Circuit( 
    cirq.X(bit) ** sympy.Symbol('alpha'), 
    cirq.Z(bit) ** sympy.Symbol('beta') 
) 
outputs = tfq.layers.ControlledPQC( 
    model, 
    [cirq.Z(bit), cirq.X(bit), cirq.Y(bit)], 
    repetitions=5000, 
    backend=cirq.Simulator(), 
    differentiator=tfq.differentiators.ParameterShift()) 
quantum_data = tfq.convert_to_tensor([ 
    cirq.Circuit(), 
    cirq.Circuit(cirq.X(bit)) 
]) 
model_params = tf.convert_to_tensor([[0.5, 0.5], [0.25, 0.75]]) 
with tf.GradientTape() as g: 
    g.watch(model_params) 
    res = outputs([quantum_data, model_params]) 
grads = g.gradient(res, model_params) 
grads 
```

Output:
WARNING:tensorflow:AutoGraph could not transform <bound method ParameterShift.differentiate_sampled of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f514e8093c8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unexpected indent (<unknown>, line 77)
WARNING: AutoGraph could not transform <bound method ParameterShift.differentiate_sampled of <tensorflow.python.eager.function.TfMethodTarget object at 0x7f514e8093c8>> and will run it as-is.
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: unexpected indent (<unknown>, line 77)
<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-3.1415927 ,  3.1415927 ],
       [-0.8947257 , -0.05277884]], dtype=float32)>

System setup, all ran from jupyter notebook:
`!lsb_release -a`
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

`import sys
print(sys.version)`
3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0]

`!python3 -m pip list | grep tensorflow`
tensorflow               2.1.0               
tensorflow-estimator     2.1.0               
tensorflow-quantum       0.2.0     

Let me know if you need anything else

**Comment by MichaelBroughton** [comment] 2020-04-18 22:50
Thank you for attaching all this information, I was able to reproduce and find a fix!

We have run into these sorts of problems before where the autographer almost gets through autographing stuff, but gets hung up on little things here and there. It looks like in this case we had some formatting that it struggled with in `parameter_shift.py`. Fix is up here #207 .

In the meantime you are safe to ignore these warnings, but if you can't stand them then once #207 is merged the latest tfq-nightly should have this fix in it.

**Closed** 2020-04-20 17:58 UTC
